### ISSUE TITLE
guide users with multiindex

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#122]
- [x] `nb_past_months` should be by default in config file, and thus be supported even if `multi_index` is set to false
- [x] multiindexing should be recommended if the tweet collection is planned to exceed 100 million tweets
- [x] give some examples from our collections
- [x] `nb_past_months` should be limited to 12 months max

**Comment by boogheta** [comment]
tu pensais à quoi comme type d'exemples from our collections?

**Comment by bmaz** [comment]
je pensais à donner les nb de tweets collectés pour des collectes passées, mais dans l'idéal il faudrait des collectes avec pas trop de mots clefs pour que ça soit clair. Je peux faire une estimation sur elasticsearch à partir de la collecte filter-links ?

**Comment by boogheta** [comment]
oki je comprends, yep why not les estimations
