### ISSUE TITLE
On gazou start, pid check should also verify process is running

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#124]
Currently when running gazou start, if the .lock file exists it returns immediately saying the process is already running, even though the process is actually not running anymore (for instance if it was force-killed by user or the machine), it would be best if the process would not only check the existence of the file but also of the process corresponding to the pid (or even better also to the processes whose parent process is the pid one to ensure that all multiprocesses are killed)

**Comment by bmaz** [comment]
the pids of the subprocesses should be stored in the .lock file after they are created. The pid can be accessed through the .pid attribute: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.pid

**Comment by bmaz** [comment]
The stop command should also stop the subprocesses listed in the .lock file
