### ISSUE TITLE
[export] Add perfs options

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#141]
- [x] use "stored_fields" in ES query to return only desired fields when using -s (except for id field which is always returned anyways)
- [x] add a nosort option to return docs faster

**Comment by bmaz** [comment]
For now, the `--sort no` works, but e.g. `--sort user_id` works only if `--index` is set to one specific index (or with mono-index)
- [ ] I need to change the yield_scans() and yield_step_scans() behavior in order to be able to sort across multi-indices.

**Comment by boogheta** [comment]
-[ ] document in readme example uses of --sort (and remind that by default it uses timestemp_utc which should be preferred to id)
