### ISSUE TITLE
JSONL export/streaming script to make it out of the box prodigy-compatible

### ISSUE THREAD

**Issue by Guillaume-Levrier** [medialab/gazouilloire#29]
Prodigy/spaCy models [apparently ](https://prodi.gy/docs/workflow-first-steps#load-data) work best with [JSONL](http://jsonlines.org/). Having an script dedicated to exporting a specified period of time from a gazouilloire corpus in JSONL would be great.

**Comment by boogheta** [comment]
It also says a CSV with a column named "text" will work fine, and it is really lighter as it does not repeat the characters of all fieldnames on each line, so I don't feel like this is quite critical.

**Comment by Yomguithereal** [comment]
Yes, the docs indeed mention that you can feed CSV without further ado: https://prodi.gy/docs/api-loaders so it's probably just a matter of renaming columns and pre-filtering the file.
