### ISSUE TITLE
Filter by user_screen_name

### ISSUE THREAD

**Issue by Free16t** [medialab/gazouilloire#3]
Hi, 

Is there a way to filter (in the config file) by the screen_name in order to have only keywords on specific accounts ? 

Sincerely

**Comment by boogheta** [comment]
You can put a @USER as keyword to follow all tweets from USER, but there's no filter possible for now nope.

**Comment by Free16t** [comment]
Ok thank for your answer, I can do the filter after with a parser.

Sincerely
