### ISSUE TITLE
Indexing tests

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#34]
Features to test:
- ~[ ] deleted tweets are marked as deleted -(procedure : add a user in keywords, pst then delete with this user and check the tweet was updated)~
- [x] "stream", "search",... tags are there

**Comment by bmaz** [comment]
It seems that we do not get deleted tweets

**Comment by boogheta** [comment]
Ha, maybe they dropped the feature?

**Comment by boogheta** [comment]
So it looks they still advertise it here: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/overview but still I could not reproduce it anymore either with a user or a keyword, so it looks like they stopped emitting these tweet deletion messages. Maybe we can drop all the code related to it from the codebase then, it would simplify it a little bit (but that's not really a priority, I'll make a dedicated card outside the milestone)
