### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#38]
- [x] source < 1024 not useful any more
- [x] catch multithread resolving errors (cf https://github.com/medialab/gazouilloire/commit/fa5c58a0e8c4cd6f385c708ec1f638909937172d?branch=fa5c58a0e8c4cd6f385c708ec1f638909937172d&diff=unified#diff-9e61678f6d25ee73ad5ba89d46aae3a3R93 )
- [x] replace "db_conf" argument by "host", "port", "db_name" in complete_link_resolving_v2
- [x] "coordinates" is LONG:LAT while "geo" is LAT:LONG
- [x] rename update_tweets_with_links --> update_retweets_with_links
- [x] normalize_url called twice on same url
- [x] use os.path.join("..", "..", ...) instead of os.path.dirname(os.path.dirname(os.path.dirname in elasticmanager
- [x] in resolve_thread, the `todo =` line can probably be moved within the while and used only once since todo is not used in the while condition (this probably supposes to init done to 0 before though)
- [x] remove old resolver code in run.py and rename resolve_thread
- [x] update reply_count only if the value exists in the new tweet

- [x] remove references to analyzer in doc and in config.json

- [x] --verbose and --silent have same behavior in gazou resolve

- [x] store date of tweet in 2 formats : timestamp (UTC time) and iso (local time)

**Comment by boogheta** [comment]
Merci ! :) 
J'ai transformé ça en checklist et ajouté les 3 autres petits trucs que j'ai repérés et pointé un choix à faire pour le raise
