### ISSUE TITLE
Backup/ReImport elasticsearch index

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#44]
- [ ] add shell script in bin to build a dump of a specific ES index
- [ ] add shell script in bin to import a dump from a previous export (with an option to overwrite the existing or complete it?)

(these actions corresponded to the scripts [bin/dump_corpus.sh](https://github.com/medialab/gazouilloire/blob/v0.1-python2-mongodb/bin/dump_corpus.sh) and [bin/import_corpus.sh](https://github.com/medialab/gazouilloire/blob/v0.1-python2-mongodb/bin/import_corpus.sh) in v0.1)

**Comment by bmaz** [comment]
The easiest way to do it is to use https://github.com/elasticsearch-dump/elasticsearch-dump

It requires to install npm, is it problematic for a python project?

**Comment by bmaz** [comment]
test npm speed

**Comment by boogheta** [comment]
As discussed, it sounds like embedding a node packlage within gazouilloire would be wveird and overkill, let's just document its use in the readme maybe?
