### ISSUE TITLE
[resolver] Retry urls in error

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#50]
Currently we detect and log urls for which the resolver failed with an error that is not a redirect one but we do not stop there and save them in db as if they just worked without redirection. Those should rather be retried at least a number of times.
So before we setup a smart way (using the future redis store) to retry them for a few days before giving up, we should just retry them in loop.

**Comment by boogheta** [comment]
Distinct behavior in run mode and posterior script mode : 
- [ ] in run mode only try to resolve urls for the last 30 days (adjustable as option in config such as resolving_delay ?) and retry in a loop
- [ ] in script mode, try everything, but no retry

**Comment by bmaz** [comment]
What should appear in the logs ?
2021-06-21 11:19:45,282 - MainProcess [12182] - DEBUG - None error: http://nws.mx/tv --> https://www.newsmaxtv.com/findus

**Comment by bmaz** [comment]
Add gazou stop --resolve ?
