### ISSUE TITLE
User needing help?

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#59]
Hello @tozmachine, we noticed your cry for help within the wiki, which is not the most appropriate way to get some support.
Please rather describe here in this issue your questions and maybe we can try and help.
Best,

**Comment by tozmachine** [comment]
I'm really sorry 🙂 I've deleted it just after seeing there is a support page !
________________________________
De : Benjamin Ooghe-Tabanou <notifications@github.com>
Envoyé : jeudi 11 février 2021 14:39
À : medialab/gazouilloire <gazouilloire@noreply.github.com>
Cc : tozmachine <tozmachine+github@hotmail.com>; Mention <mention@noreply.github.com>
Objet : [medialab/gazouilloire] User needing help? (#59)


Hello @tozmachine<https://github.com/tozmachine>, we noticed your cry for help within the wiki, which is not the most appropriate way to get some help. Please rather describe here in this issue your questions and maybe we can try and help.
Best,

**Comment by tozmachine** [comment]
Hello, do you want me to remove post and copy it here ?

**Comment by boogheta** [comment]
Yes thank you, that would be way better

**Comment by tozmachine** [comment]
Hello
Could you please help ?
I would like to setup gazouilloire but the setup documentation is light and I'm beginner on Docker (thats why I think it's light... for me :-).

I seems that docker is the best way to setup Gazouilloire:

 ` Install gazouilloire`
Ok I've setup docker on my windows laptop.
Downloaded and setup python image (as I saw that next command will be `pip`
**Run** container with settings:
**Volumes**
host path: C:\Docker\Gazouilli
Container Path : empty (I've issue if I want to use folder)

`pip install gazouilloire`
It's working fine

  ` Install Elasticsearch (version 7.X)`
mmm... ok I've downloaded the docker image and **ran** it
It's seems to work
Question: do I have to create a sort of bridge between the 2 containers ? 
I continue, I will see if this is blocking.

`    Init gazouilloire collection in a specific directory...
    gazouilloire init path/to/collection/directory`
Not working, I think there is something wrong with path / Docker and windows but I don't see any documentation relevant for me.

```
    ...or in the current directory

    gazouilloire init
```
Yeah, this is working ! I can continue

`a config.json file is created. Open it to configure the collection parameters.`
mmm here i'm blocked , where can I found it ?
I've search on all my C:\ and didn't found any config.json file.
Question: where are stored the file ? 
Is ther any "how to" edit file somewhere ?

I'm really locked at this time and would really appreciate help on your side.
Thanks a lot

**Comment by boogheta** [comment]
Hello again,
I apologize in advance, but this library is intended for people having a minimum knowledge of python installations ideally, we won't be able to help you for the whole process of making python work and install packages on windows, you should read online tutorials about this part.
Although if I understant correctly what you did, you installed python from within a docker container and ran pip install gazouilloire within it. This should work but we haven't prepared anything for it yet and it will probably require some kind of bridging indeed which we can not advise you much on yet: we only recommand to use Docker for ES for now, the python part should be easier to do without Docker. This also probably explains why you cannot find the config.json file on your system: it is inside your docker container and should be opened from within, or from the outside by setting up a volume. But here again, we won't be able to teach you how to work with Docker.
Can you maybe try and install python differently, for instance by using conda or anaconda?

**Comment by boogheta** [comment]
I close this issue for sping cleanup, please reopen it if you're still encountering some problems
