### ISSUE TITLE
gazou resolve should take current folder config to find db_name

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#62]
db_name could be an optional argument

**Comment by Yomguithereal** [comment]
If so, I think we should move to no positional arguments and rely on `-p/--path` to load conf as with other metrics, or do you have a specific use case in mind where you want to hit a specific ES db outside of the scope of a gazouilloire configuration?

**Comment by bmaz** [comment]
For other commands, `-p/--path` takes the current directory as default, I think the same behaviour should be expected from resolve.

Concerning a potential `db_name` argument, it can be justified by the fact that `gazou resolve` (as well as `gazou export`)  does not need any Twitter configuration to work, and could potentially run without a gazouilloire configuration file

**Comment by boogheta** [comment]
I think I agree with @bmaz 
So if I understand properly, the idea would be to priorily take account of db_name if it is given, then to a config found in -p/--path and finally to a config found in the current dir

**Comment by Yomguithereal** [comment]
`gazou resolve` now has `-p/--path` and `--db-name` as described. @bmaz I did not replicate this for the `export` command just yet because it needs the `grab_conversations` key from config and I am not sure what to do if we only have the database name in this case.

**Comment by boogheta** [comment]
Yep I'm not sure having a gazou export without the config makes much sense, so I would not try to add the --db_name to gazou export
So I'm closing this one for now
