### ISSUE TITLE
Add a way to get the list of availables fields from CLI

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#66]
Either a dedicated CLI route, for instance gazou export --list_fields, or better : directly within gazou export --help within the -c/-s doc  part

**Comment by Yomguithereal** [comment]
I've added the full list in the command's help. The list is quite large though. We can try to condense, or leave it like that or roll back to something like `--list-fields`. What do you think?

**Comment by boogheta** [comment]
I concurr, the list is way too long to be included in the regular help, we do not even see the top of the help
