### ISSUE TITLE
Multiprocessing issue with mac

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/gazouilloire#71]
Gazouilloire's multiprocessing fails on macOS for python 3.8 because of changing multiprocessing defaults (regarding spawn/fork etc.) and because of subtle issues related to pickling items existing in local scopes.

I see ~3 possible solutions (sorted by amount of work they require):

1. Just prevent people that they should use python 3.7 for gazouilloire to work on mac for the time being.
2. Use `multiprocessing.set_start_method("fork")` as explained in [this](https://github.com/pytest-dev/pytest-flask/issues/104). This should be done cautiously (maybe by detecting the os/pyversion running gazouilloire) as it could cause other unwanted issues on systems where gazouilloire currently work (this should also mess up windows, I think).
3. Use [`dill`](https://pypi.org/project/dill/) to handle pickling.

**Comment by Yomguithereal** [comment]
I can reproduce this issue on my own mac :)

**Comment by boogheta** [comment]
Ha this explains why the problem didn't happen before when people used gazouilloire v0.1 with Mac OS.

I feel like solution 1 should be implemented quickly while exploring solutions 2 and 3.

I don't know about dill, do you feel like it could affect performance? would that mean overloading the regular multiproc libs?

**Comment by Yomguithereal** [comment]
I am doing some tests with solution 2. right now.

> I don't know about dill, do you feel like it could affect performance? would that mean overloading the regular multiproc libs?

dill won't have any performance cost in gazouilloire case since it should only be used with client instances and maybe some other things but only when initializing the procs. But this adds a cost on the source code because you need to handle serialization explicitly while python usually does it for you automatically.

**Comment by Yomguithereal** [comment]
Hmmm. the problem is in fact a bit more complex than foreseen because the default start method was changed for good reasons: https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods
