### ISSUE TITLE
[export] Handle more complex ES queries

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#77]
Currently gazou export already allows many possibilities, but if we want to run complex ES queries we cannot and have to either call ES directly or postfilter the results with xsv for instance.
Here are a few usecases we should think how to handle:
- text query with AND (i.e. : A && B)
- text query with combination of AND and OR (i.e. : A || (B && C) || (D &&C)
- existence/inexistence of some specific fields such as to_tweetid, quoted_id, media_urls, links etc (currently we have this for retweeted_id (--exclude-retweets) and match_query (--exclude-threads) only)
- combination of AND and OR with existence of such fields (i.e. :  (text contains supprim[eé] or signal[eé]) AND (not retweet) AND (not thread) AND ( (to_tweetid exists) OR (quoted_id exists) OR (media_urls exists) ))
- TBC...

edit: in a first time (and maybe for all times for some of the complex cases above), we could maybe simply add a --raw-query argument that would override all other arguments and let one write directly its own ES query maybe

edit2: it looks like we could benefit also from the possibility to run [raw query_string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) on the text as well to be able to write things such as A OR (B AND C)

**Comment by bmaz** [comment]
related to https://github.com/medialab/gazouilloire/issues/121

**Comment by boogheta** [comment]
I think this one could be closed as well, on two conditions : 
- [ ] document it in the readme with examples of lucene queries and AND/OR ones
- [ ] demonstrate and give examples of how to query on existing/missing/empty fields

**Comment by bmaz** [comment]
From what I understand, there is no way to query empty strings: `NOT my_field:*` is equivalent to `NOT _exists_:my_field` and would only match documents where the field is missing or with a null value. 

Fields that are affected by this problem:
- user_location : the field always exists but may contain an empty string
- user_description : idem
- user_image : never exists or always null ???

==> Should we replace empty strings by None values for user_location and user_image?

**Comment by bmaz** [comment]
https://github.com/medialab/twitwi/commit/9fcaa2a0d10794de0a0f5f0c56c28a96a26ee489
