### ISSUE TITLE
Fix more cases of ?s= in twitter urls

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#84]
We only handle s=19 but more cases can happen, cf here https://github.com/medialab/gazouilloire/blob/elasticPy3-merge/gazouilloire/url_resolve.py#L52
Laybe fix them all with a regexp instead

**Comment by Yomguithereal** [comment]
As a reference, `ural` strips any `s=` query on `twitter.com` using [this](https://github.com/medialab/ural/blob/master/ural/normalize_url.py#L73) filter. I have seen `s=04` to `s=21` in the wild.
