### ISSUE TITLE
Option for gazou export to not return headers?

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#94]
In some cases one might want to assemble results of multiple gazou exports call into one which could be simplier with an option to skip headers

**Comment by Yomguithereal** [comment]
`xsv behead` muahahahahah

**Comment by bmaz** [comment]
`xsv cat` plutôt

**Comment by boogheta** [comment]
ouais mais bon...
Je fais déjà grep -v '^id' mais l'idée était justement de ne pas avoir à piper et reposer sur un truc externe

**Comment by boogheta** [comment]
bon allez je ferme, c pas une prio pour dans gazou clairement
