### ISSUE TITLE
Avoid None values in plural fields such as collected_via, mentioned_ids, etc.

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#97]
This is the original problem with of the issue reported in twitwi : https://github.com/medialab/twitwi/issues/25
for now, None values are replaced by empty string at export, so we may get collected_via:|search

**Comment by boogheta** [comment]
it seems like this error can also happen within the mentionned_ids field (one case met with tweet  1392474405729705984  )

**Comment by boogheta** [comment]
@bmaz Isn't this fixed now?

**Comment by bmaz** [comment]
Could not reproduce.
